### ISSUE TITLE
[Feature] Custom props in next-slicezone

### ISSUE THREAD

**Issue by samlfair** [prismicio/slice-machine#102]
@hypervillain added Custom Props to `vue-slicezone`: https://github.com/prismicio/slice-machine/pull/67

[As user on the forum asked](https://community.prismic.io/t/can-you-pass-props-down-to-the-individual-slice-components/5128) if you can pass custom props in `next-slicezone`, which I don't think is possible currently. Could we add custom props in Next?

**Comment by drewlonious** [comment]
Yes, to piggy back on what @samlfair is saying, would love to pass custom props into next-slicezone! There are some usecases for this, being extremely useful. Would love any insight as to whether or not this is possible.

**Comment by hypervillain** [comment]
This is possible and will be done next week

Envoyé de mon iPhone

**Comment by hypervillain** [comment]
I just published `next-slicezone@0.1.0`. You should be able to pass a `sliceProps` prop to the SliceZone (object or function). We also made some changes to the `useGetStatic` -Paths and -Props calls:

1/ `params` has been renamed to `apiParams`
2/ No more `uid` or `lang` params, use `apiParams: { uid: '', lang: '' }` instead
3/ We added a `getStaticPathsParams` prop that gets passed to return object of `getStaticPaths`

Can you give it a try and tell me how it goes?

**Comment by hypervillain** [comment]
WIP README: https://github.com/prismicio/slice-machine/tree/master/packages/next-slicezone

**Comment by wasinsandiego** [comment]
Thanks for this!
How would I install `next-slicezone@0.1.0`? The highest version I been able to install is ~0.1.5~ 0.0.15.

- Edit: I had a typo on the version I was able to get installed. It's actually 0.0.15 and I got that by `npm install next-slicezone@latest`.

**Comment by hypervillain** [comment]
Hey Will, you need to install ***@***.***` to target the latest
version that was tagged alpha on npm

**Comment by wasinsandiego** [comment]
@hypervillain Thanks for the reply!
Wondering perhaps if some text replacement happened in your message? I'm seeing a bunch of asterisks in your example instead of the package name and version.

On the chance the asterisks were intentional to illustrate removal of the minor semver digit, I did try `npm install next-slicezone@0.1` without luck. Is this a situation where I need to clone and build locally to develop against this feature? Asking because when I do `npm view next-slicezone version` it shows the latest version in the npm registry as `0.0.15`.

Sorry if I missed some documentation or missing something obvious 😅  I really appreciate the help!

**Comment by hypervillain** [comment]
That was non intentional haha, I believe Github thought it was an email address.
Try `next-slicezone@alpha` 😊

**Comment by hypervillain** [comment]
This was merged. We'll also release a `0.1.0` which is in alpha right now. Feel free to give it a try
