### ISSUE TITLE
Login doesn't work (v0.7.0)

### ISSUE THREAD

**Issue by kb1995** [prismicio/slice-machine#1021]
### Versions

- slice-machine-ui: 0.7.0
- node: 18.12.1

This is a critical bug (I also posted it in the community forum - https://community.prismic.io/t/slice-machine-cant-push-changes-as-im-constantly-logged-out/13509/2)

My company is not in a position to upgrade to >1.0 now (I'm also not sure if this bug is caused by being on 0.7 as one of my colleagues doesn't have this issue), but for now when I tried to create a new slice and push it to the Prismic repo, I get an error that I'm not logged in even after I get a success message I'm logged in. Thus I'm stuck in an infinite cycle. What can I do to be able to push changes to Prismic.
<img width="333" alt="Screenshot 2023-06-26 at 11 17 50" src="https://github.com/prismicio/slice-machine/assets/32920882/4b02ba9d-5812-4ba2-8621-2dc22347feb0">
<img width="907" alt="Screenshot 2023-06-26 at 11 17 55" src="https://github.com/prismicio/slice-machine/assets/32920882/78ec0cbe-a93d-48b5-8e73-9be36174dd85">
<img width="378" alt="Screenshot 2023-06-26 at 11 17 59" src="https://github.com/prismicio/slice-machine/assets/32920882/1febff28-6b61-4bc3-8140-23f305356983">

**Comment by mdeclercq** [comment]
Hi @kb1995,

Thanks for reporting the issue. 
We were not able to reproduce it and have a few questions to get a better understanding. 

- When did this work for the last time?
- Do you encounter the error on other repositories too?

You mentioned your colleagues don't have the issue so I suppose the configuration is fine. But I need to ask:

-  Could you double-check the configuration to ensure the repository name is correct? In particular this line from the `sm.json` file
```javascript
 "apiEndpoint": "https://<repo name>.cdn.prismic.io/api/v2"
```
- Could you check if you have access to the repository documents list on Prismic: `https://<repo name>.prismic.io/documents/`

The reason I am asking this is because SliceMachine doesn't properly handle the case where a user tries to access a repository it can't read. 
This can happen when the user doesn't have the permission on the repo or if the repo is misspelled. When this happens, it shows the `Logged in` confirmation message but never allows to push changes, just like in your screenshots.

Thanks,

**Comment by kb1995** [comment]
@mdeclercq Thanks for the reply!

1. It has never worked for me - I recently took over this repo and I just tried to publish a new change but it didn't work
2. I haven't encountered this in other repos
3. sm.json is correct
4. I do have "Writer" access to the repo

The only thing on my mind is that I need to have admin access in order to push slice machine changes. Is that the case?

**Comment by mdeclercq** [comment]
Thanks for replying @kb1995,
You're right, as SliceMachine involves editing Content Types / Slices, you need to ask an Admin or Repository owner to give you the Administrator permission.
You can find more information about roles on https://prismic.io/docs/guides/manage-users#user-roles.

Let us know if that solves the issue.

Fyi, the team is aware that this kind of scenario could be handled better by SliceMachine but it's not a priority to fix it right now.

**Comment by kb1995** [comment]
Thanks @mdeclercq - this fixed the issue! I'm surprised that there is not at least a warning to point me in the right direction...

**Comment by mdeclercq** [comment]
Glad to see this resolved the issue.

> I'm surprised that there is not at least a warning to point me in the right direction...

We created an internal ticket to improve that.

**Comment by codermuyi** [comment]
slice-machine-ui: 10.2.3
I am experiencing the same issue but I am an Administrator and the repository owner. I haven't been able to push any models.
