### ISSUE TITLE
[Slice Machine] Slice Machine can't render your Slice (frame origin blocked)

### ISSUE THREAD

**Issue by Charlene-Bx** [prismicio/slice-machine#1038]
### Versions

- slice-machine-ui: v1.4.0
- node: v16.19.0

### Steps to reproduce

1. Create a new Prismic project then run slice machine on localhost:9999 and npm server on localhost:3000
2. Create a new Slice, and on the slice machine, click on "simulate slice"
3. On http://localhost:9999/.--slices/ImageTextBloc/default/simulator get few errors in the console:
<img width="1792" alt="Screenshot 2023-07-09 at 14 21 38" src="https://github.com/prismicio/slice-machine/assets/70715305/7ab891bd-e7da-49b3-adf1-6e2cd470f38b">

### What is expected?
Be able to simulate the slice

### What is actually happening?
The page load for some time, then an error appears and errors message appears in the console.

**Comment by hypervillain** [comment]
Hi, you mentioned running `npm server`, does it mean your project is based on a nodeJS server?

**Comment by Charlene-Bx** [comment]
Hi!
Indeed it is!

Le mar. 11 juil. 2023 à 15:09, Hugo Villain ***@***.***> a
écrit :

**Comment by cricadev** [comment]
Hey, did you manage to solve it?

**Comment by cricadev** [comment]
@Charlene-Bx did you manage to solve it?

**Comment by Charlene-Bx** [comment]
Still not. I’ve tried multiple time to reinstall the project but get always
the same result.

**Comment by mdeclercq** [comment]
Hi @Charlene-Bx,

Thanks for reporting. Are you using the Nuxt pages directory? See the [Nuxt docs](https://nuxt.com/docs/guide/directory-structure/pages#usage) or [Prismic docs](https://prismic.io/docs/nuxt-3-setup#:~:text=Create%20a%20pages%20directory%2C%20move%20the%20app.vue%20file%20into%20that%20directory%2C%20and%20rename%20pages/app.vue%20to%20pages/index.vue%3A) ? 

What happens when you try to access the slice simulator page directly on http://localhost:3000/slice-simulator ? 
It should show this:
<img width="699" alt="image" src="https://github.com/prismicio/slice-machine/assets/6433957/5e0ce1da-49ef-4133-a52c-be774e6bb86e">

Your screenshot shows 2 errors: `Blocked a frame with origin` and `Connection timed out`.
The first one comes from Nuxt devtools. You can temporarily disable Nuxt devtools by setting `devtools: { enabled: false },` in `nuxt.config.ts` but I don't think it will solve the issue.
The second error seems to be the blocking one, probably because http://localhost:3000/slice-simulator shows something else than "Slice Simulator"

The issue looks similar to https://github.com/prismicio/slice-machine/issues/1051

Thanks,

**Comment by Charlene-Bx** [comment]
Indeed, http://localhost:3000/slice-simulator show me the Nuxt welcome page. 
Moving app.vue into pages directory with `mv app.vue pages/index.vue` fix it!

Thanks!
