### ISSUE TITLE
Provide a better error message when user Content Security Policy prevent the simulator from being embedded

### ISSUE THREAD

**Issue by loick** [prismicio/slice-machine#1042]
Hi, I'm trying the Slice Simulator and it does not seem to be working for me. Here is what I get: 

<img width="1440" alt="CleanShot 2023-07-10 at 17 05 29@2x" src="https://github.com/prismicio/prismic-react/assets/4931832/6786dfc4-02e7-4753-99a2-f612e23ea778">

## Context
I'm using this documentation: https://prismic.io/docs/technical-reference/slicemachine-adapter-next
So I basically have in my component: 

```js
import { SliceZone } from '@prismicio/react'
import { SliceSimulator as PrismicSliceSimulator } from '@slicemachine/adapter-next/simulator'

import { components } from '../slices'

export const SliceSimulator = () => (
  <PrismicSliceSimulator
    sliceZone={(props) => <SliceZone {...props} components={components} />}
  />
)
```

This component is then used in a Page component within my app: 
```js
const SliceSimulatorPage = () => {
  return <SliceSimulator />
}
export default SliceSimulatorPage
```

Might help as well, here is my slicemachine config: 
```json
{
  "apiEndpoint": "https://slowy.cdn.prismic.io/api/v2",
  "repositoryName": "slowy",
  "adapter": {
    "resolve": "@slicemachine/adapter-next",
    "options": {
      "lazyLoadSlices": false
    }
  },
  "libraries": ["./src/slices"],
  "localSliceSimulatorURL": "http://localhost:3000/slice-simulator"
}
```

And these are the prismic versions I'm using: 
```json
{
  "@prismicio/client": "7.1.0",
  "@prismicio/next": "1.3.3",
  "@prismicio/react": "2.7.1",
  "@slicemachine/adapter-next": "0.3.3",
  "prismic-cli": "4.2.3",
  "slice-machine-ui": "1.3.0",
}
```

The only package I'm not up to date on is the slice machine because of the other bug reported here: https://github.com/prismicio/prismic-react/issues/189

Please, let me know if I can be of any help. 

👋

**Comment by lihbr** [comment]
Hey @loick, thanks for the comprehensive issue again.

I'm curious about this error you're getting:
![image](https://github.com/prismicio/prismic-react/assets/25330882/742ea9bb-8d95-4de1-b9ca-92d40e31b958)

Any chance you have some Content Security Policy set up on your website? Maybe something like [Next.js headers](https://nextjs.org/docs/pages/api-reference/next-config-js/headers), React Helmet or something similar? If so, can you try disabling/loosening them for the Simulator page? (at least the `X-Frame-Options` one which prevents a page from being embedded)

This *could* be caused by a Chrome extension also, if you're not sure about CSP, can you try running it in a guest session to be sure?

Let us know about it ☺️

**Comment by loick** [comment]
Oh yeah indeed you're right, I didn't check that part, my bad. I indeed have this header in place 😬

**Comment by lihbr** [comment]
No worries! We should try to detect that so we can provide a better error message ☺️

I'm transferring this issue to the Slice Machine repository 🚀

**Comment by comeprismic** [comment]
Hi, 
The team decided to not prioritize a fix for this issue for now. I close this issue, it can be used as a reference for any user that encounters the problem in the future. 

Thanks again for submitting it.

All the best
