### ISSUE TITLE
Choose folder where customtypes can be stored

### ISSUE THREAD

**Issue by madiyetov** [prismicio/slice-machine#1053]
### Is your feature request related to a problem? Please describe.

I want to create a complex structure with slices + `customtypes`. And at the same time keep it in a package.
Now I can choose where to store slices, but not `customtypes`. Which is a blocker to keep them together.

### Describe the solution you'd like

Ability to choose folder where to store customtypes the same way as for slices.

**Comment by hypervillain** [comment]
There is no possibility to pick at custom path for custom types because they're defined at the project level. I'm adding this to our backlog but I don't think we'll tackle this anytime soon. There might be a possibility to do this once we make plugins management public. I will re-open the issue once it's ready on our side. Sorry for the inconvenience!
