### ISSUE TITLE
Cannot publish / update anything

### ISSUE THREAD

**Issue by loick** [prismicio/slice-machine#1091]
Hi, I cannot publish anything from the slicemachine. It says "No internet connection" even though everything else is working properly (And yes I have internet connection :)). 

### Versions

```
{
    "@prismicio/client": "7.1.0",
    "@prismicio/next": "1.3.3",
    "@prismicio/react": "2.7.1",
    "prismic-cli": "4.2.3",
    "slice-machine-ui": "1.7.1",
}
```

### Reproduction

1. Login to prismic with the CLI: 
```
prismic login
```

![CleanShot 2023-08-03 at 18 34 49](https://github.com/prismicio/slice-machine/assets/4931832/203a5911-3ca5-4090-8534-c4593112b63b)

![CleanShot 2023-08-03 at 18 35 02@2x](https://github.com/prismicio/slice-machine/assets/4931832/9887d844-de5d-4236-b5dd-9e161fec5f89)

2. Update something on your custom types

3. I'm still considered as logged out 
![CleanShot 2023-08-03 at 18 33 57](https://github.com/prismicio/slice-machine/assets/4931832/9a7c88f4-c76a-435d-94f2-1afca4b192c6)

Any idea how to publish?

**Comment by mdeclercq** [comment]
Hi @loick,

Thanks for reporting the issue. 
I could not reproduce it myself but I have a few questions that could help us investigate.

- Did this just start happening with the version `1.7.1` of SliceMachine ? Did it work in other versions ?
- Which browser (and version) are you using ?
- You mentioned you see the message `No internet connection`. Could you type `window.navigator.onLine` in the browser javascript console and send us the evaluated value ? I'm asking because there were cases of false positives reported for Chromium [here](https://bugs.chromium.org/p/chromium/issues/detail?id=678075), the most recent comment suggests to disconnect and reconnect the network to fix it.
- Does it work with another browser ?

In the meantime, the workaround would be to run `npx @slicemachine/init@latest` which pushes the Custom Types and Slices without going through the browser.

Thanks,

**Comment by loick** [comment]
Hi @mdeclercq, 

it seems to be working today, so I guess we can close this one. I didn't change anything and I'm on the same configuration as yesterday. I tried for several hours yesterday and it was not working but it seems to be fine now. I'll post again on this issue if it's happening again with the info you asked me.

**Chrome version**: 115.0.5790.170
