### ISSUE TITLE
NextJS 11 : useGetStaticProps and useGetStaticPaths not compatible with latest linting rules

### ISSUE THREAD

**Issue by asotog** [prismicio/slice-machine#131]
### Version

prismic-cli: 3.8.13

### Reproduction

create a nextjs site and try to use prismic hooks on any page https://prismic.io/docs/technologies/technical-reference-next-slicezone-nextjs  like 
```
export const getStaticProps = useGetStaticProps({  ...
```

### What is expected?

Linting should not complain

### What is actually happening?

Linting is complaining, because a hook is used outside of a component

**Comment by lihbr** [comment]
Hey @asotog, thanks for reporting that to us!

We're planning to rework the Next integration with Prismic, not using those Prismic hooks anymore, more info about that here: https://github.com/prismicio/prismic-next/issues/1 (and more than happy to discuss our plans with you there!)

I don't think (except further notice), that we will change that naming for the current kit (and it would introduce a breaking change anyway for current users) so I'd suggest you use ESLint ignore comments on those lines.

To give you more context those functions are not React hooks and the assumption of ESLint is wrong here because only based on the function `use` prefix. To some extent this is more of a bug with ESLint React integration than with this kit, not diminishing the fact we didn't follow React code standards there.

Let us know if anything and feel free to reopen this issue if you think this needs more discussion!
