### ISSUE TITLE
slice-machine doesn't allow snake_case api ID, GraphQL api hides camelCase.

### ISSUE THREAD

**Issue by happylinks** [prismicio/slice-machine#222]
### Versions

- slice-machine-ui: 0.1.0
- node: 16.13.0

### Reproduction

![image](https://user-images.githubusercontent.com/184774/141298477-14824eca-159f-483d-8690-432f1b8971e1.png)
Adding snake_case api ID's gives the error that you can't use special characters.
However, there's still an issue with the GraphQL api that hides camelCase attributes: https://community.prismic.io/t/camelcase-named-fields-are-missing-in-graphql-explorer-and-introspection/3040/7

So, now I manually add the snake_case API ID's in the json.

Either slice-machine should accept snake_case, or the issue with the GraphQL api needs to be fixed. Else I can only make attributes with no casing at all.

**Comment by VilliGunn** [comment]
Just to add to this. When creating custom types in Prismic the default value generated in the `API ID*` is a snake_case value, so there is an inconsistency there.

![Screenshot 2021-11-18 at 13 23 01](https://user-images.githubusercontent.com/17431581/142423410-12f62b84-810d-4298-8df0-2400b1b8485c.jpg)

I have opened a pull request that allows snake_case values when creating Field Ids since this only seems to be blocked client side and no validation done when pushing custom types and slices to Prismic from the Slice Machine. #225

**Comment by VilliGunn** [comment]
It looks like this has been fixed in #520 so this issue can be closed.

@happylinks

**Comment by happylinks** [comment]
Thanks!
