### ISSUE TITLE
Generate TypeScript types from slice schemas

### ISSUE THREAD

**Issue by jackpordi** [prismicio/slice-machine#355]
### Is your feature request related to a problem? Please describe.

As a typescript developer, I'd like slices (and custom types/documents) to be fully typed.

### Describe the solution you'd like

It would certainly be nice if slice-machine could generate TypeScript types for us automatically. I don't think this is particularly hard, as slice machine is already generating a `model.json` with all the information required to generate types.

E.g it should be simple enough to generate something like this:

```typescript
export interface IMyCustomSlice {
  title: string;
  image: PrismicImage; // defined elsewhere in your libs
}
```

To further build on this, we would probably be able to generate type-guard functions as well in order to enable devs to build custom `SliceZone`-like components and logic:

```typescript
export interface IMySecondSlice {
  text: string;
  bannerImage: PrismicImage; // defined elsewhere in your libs
}

export type Slice = IMyCustomSlice | IMySecondSlice

function isMyCustomSlice(slice): slice is IMyCustomSlice {
  return slice.slice_type === "my_custom_slice";
}
```

### The current alternative

Have to hand write types and type guards ourselves.

**Comment by EddyVinck** [comment]
I've thought about this as well. I currently don't have the time to work on it though, but it would be nice!

**Comment by mdeclercq** [comment]
Hi @jackpordi, Thanks for submitting the idea!
SliceMachine generates Typescript types since the version `0.5.1`. You can find more information in the [release notes](https://github.com/prismicio/slice-machine/releases/tag/slice-machine-ui%400.5.1) and the [Prismic documentation](https://prismic.io/docs/slice-machine#typescript).
I am closing this issue, feel free to open a new one in case you encounter any issue.
