### ISSUE TITLE
migrate fails, no config supplied

### ISSUE THREAD

**Issue by myatt95** [prismicio/slice-machine#56]
https://github.com/prismicio/slice-machine/blob/b36fa8b30c99f050356befe8671b4b368e6914b1/packages/slice-machine/server/api/migrate.js#L33

should `config` be supplied here to `getLibrariesWithFlags()`?

**Comment by lihbr** [comment]
Hey @myatt95, nice catch! We'll try to sort that out quickly @hypervillain can you have a :eyes:?

**Comment by hypervillain** [comment]
We actually got rid of the migration with version 0.0.39, it should now only happen in file system. Can you give it a try again? If you see a "Name conflict" tag on the component or when you hover on it, this is because the (PascalCased) name of your folder needs to match with the (hyphenated) id of your component. Feel free to change any of those right from your file system.

To debug further, you can access the actual error from your browser console. In the produced logs, you should be able to access all loaded information in the `libraries` log. The migration part definitely needs more polishing, thank you for reporting that ✌️

**Comment by lihbr** [comment]
Has been fixed 🥳
