### ISSUE TITLE
RFC: Add support of the `pull` command in the Prismic CLI

### ISSUE THREAD

**Issue by arnaudlewis** [prismicio/slice-machine#8]
## Summary

We want to add a way to synchronize your components between Prismic and your project.
It would be a CLI command that will scan all your slices on Prismic side and all your slicemachine components on the other side to help you create the missing ones and update the others if needed.

## Motivation

The goal of Slicemachine is to have a more code-centric approach and avoid all these steps of simply synchronizing your setup on Prismic and your project.
The CLI is supposed to be here to resolve this connection and automate things for you.

Here we face the case where you add Components from the Writing Room that is connected to all of our Slicemachine Libraries.
You can even imagine that these slices that already exists in your project might have been updated since then.
So here, it's just a quick way to resolve these cases seamlessly.
## Scenario
Let's say that you just setup your project for SliceMachine with the following command:
```
> prismic sm --setup
```

It created 3 slices:
 - CallToAction
 - Banner
 - HighlightItems

At some point, you decide to change the models of `CallToAction` and `Banner` and to add a new slice called `HelloWorld` from the writing room.
You can use the following command to update your project accordingly:
```
> prismic sm --sync

These slices were added to your project:
 - HelloWorld

Conflicts on the custom type `page`.
All these components already exists but their model diverge.
Select the components you'd like to update:
 [ ] CallToAction
 [x] Banner

 We successfully updated the model of:
  - Banner

Please update your implementation accordingly.
```

## implementation

- Create a new command `--sync` for slicemachine that will be recognize by the CLI.
- Gather all the models of the slices coming from the different libraries listed in `sm.json`
- Fetch all the slices coming from your custom types through the CustomTypes API (see `create-slice` as an example)
- Make a diff between these to identify:
  - Existing slices already up to date
  - Existing slices that have conflicts because of updates on the Writing room
  - Missing slices that should be added to the project
- Create the Missing Slices
- Create an interactive way with `inquirer` (Already the dependency used for Prompts) to resolve conflicts and update or not the models in the code.

**Comment by hypervillain** [comment]
What happens in case a model has changed in one of your dependencies?

**Comment by arnaudlewis** [comment]
@hypervillain In this case, since it's a top to bottom (Prismic -> project) it would conflict and it would ask you if you want to override the model from Prismic to your project. 
That would mean two things:
- We need at some point to have a way to insert slices from your code to prismic during the setup or maybe even a sync command that works the other way around maybe
- And if it conflicts with a slice coming from a node modules, should we just notify the user to handle the conflict manually? In this case we can't really do it for him.

Happy to collect suggestions on this ;)

**Comment by hypervillain** [comment]
I think it highly depends on why a conflict arises in the first place. With essential-slices, I found multiple places where I was tempted to update models in a non-blocking way for the user. A field being added or a placeholder being re-written should not necessarily be considered as conflict. But I understand it would be tough to track down.

**Comment by hypervillain** [comment]
The more I look at the example, the more I think knowing what (which fields) changes on top of where would be really helpful.

**Comment by hypervillain** [comment]
Last note: when you mention inserting slices during the setup, the only blocker I see is that slice models don't describe in which custom types they have to be appended. This is ok when syncing from Prismic to your project but not the other way around.

**Comment by arnaudlewis** [comment]
@hypervillain I didn't quite understand your last comment

**Comment by lihbr** [comment]
Took me a bit of time to understand the sync described here but if I'm right current behavior of `prismic sm --sync` looks more like a pull than a true sync to me (which would have been applying last diffs on both sides) That's why I find it a bit misleading put that way, probably :thinking:

In my opinion, it'll be clearer to make it like `prismic sm --pull` or similar so we'll be able to work on it from that point, and then we'll be able to work on a counterpart `prismic sm --push` if needed? Both resulting to some sort of an interactive prompt allowing people to choose which contents to override and whatnot with the pull/push command (like on the example described in the given scenario).

As for slices used through dependencies perhaps it'll be simpler to introduce a third command like `prismic sm --push-deps` (not sure at all about that name), to just push/update their models to Prismic with an interactive prompt again to be sure we're not overriding anything not wanted. If we get through this path though this means that the previous pull/push commands will only care about project-level slices (not the ones from dependencies), hope that makes sense~

With all of that in mind, I think it raises few questions like how we're sure we're doing the matching correctly between Prismic slices and their models (not sure how that's done currently), also as @hypervillain pointed out what about knowing which customs types a model belongs to?

**Comment by sadache** [comment]
@arnaudlewis I am thinking maybe pull command should be followed by a slice name. So basically you need to explicitly specify the slice models that you need to pull (to avoid conflict and keep the intention)

**Comment by sadache** [comment]
> Took me a bit of time to understand the sync described here but if I'm right current behavior of `prismic sm --sync` looks more like a pull than a true sync to me (which would have been applying last diffs on both sides) That's why I find it a bit misleading put that way, probably 🤔
> 
> In my opinion, it'll be clearer to make it like `prismic sm --pull` or similar so we'll be able to work on it from that point, and then we'll be able to work on a counterpart `prismic sm --push` if needed? Both resulting to some sort of an interactive prompt allowing people to choose which contents to override and whatnot with the pull/push command (like on the example described in the given scenario).
> 
> As for slices used through dependencies perhaps it'll be simpler to introduce a third command like `prismic sm --push-deps` (not sure at all about that name), to just push/update their models to Prismic with an interactive prompt again to be sure we're not overriding anything not wanted. If we get through this path though this means that the previous pull/push commands will only care about project-level slices (not the ones from dependencies), hope that makes sense~
> 
> With all of that in mind, I think it raises few questions like how we're sure we're doing the matching correctly between Prismic slices and their models (not sure how that's done currently), also as @hypervillain pointed out what about knowing which customs types a model belongs to?

I just noticed that you basically said the same thing :)

**Comment by lihbr** [comment]
> @arnaudlewis I am thinking maybe pull command should be followed by a slice name. So basically you need to explicitly specify the slice models that you need to pull (to avoid conflict and keep the intention)

I think that having the interactive prompt where you can choose which changed-slice to override or not would be less overwhelming than having to pull each slice one by one when you, for example, checkout another branch or such. Nonetheless could be a nice addition at some point to provide more fine-grained control~

**Comment by arnaudlewis** [comment]
First implementation: https://github.com/prismicio/prismic-cli/pull/48

**Comment by julon** [comment]
Hi @arnaudlewis, its awesome that the pull feature is coming to the cli, its gonna make our use case way easier during slice development. Is the push feature to repository planned on the roadmap as well? Our full use-case would be to effectively pull the slice from a staging/dev repository(prismic) as a json during development, and through a CI pipeline to spread (hard replace) those to multiple repositories to have a single source of truth for slices which is versioned with our frontend components (nextjs) deployed on related websites. Since we planned to handle a lot of websites/repositories we can't scale without it.

**Comment by arnaudlewis** [comment]
Hi @julon, it definitely is but we’re trying to make a way for slices creator to have an optimize way to build them.
Having some kind of isolated sandboxed environment for slices and a full integration with the CLI to keep the source of truth in the code as you said :)

**Comment by arnaudlewis** [comment]
And BTW, it’s still experimental but you can already try the pull with the last alpha version of the CLI ;)

**Comment by julon** [comment]
@arnaudlewis awesome i will try that right away :)
Since we are reviewing all the features of prismic for a production use before joining, do you know approximately in range if we are talking about days or month or more? So we can know ahead if it fits our scheduled roadmap or if we need to take it into account on our part.

If you need any more details on our use case or needs for the cli, I would be happy to exchange :)

**Comment by lihbr** [comment]
Not relevant since Slice Machine UI, I'm closing that one!

**Comment by christianrybe** [comment]
@lihbr how is Slice Machine UI fixing this, sorry? 🙂 I can't find a way to `pull` changes from the UI to my local repo. How do I grab a slice that my teammate has created and pushed to Prismic?

**Comment by lihbr** [comment]
Hey @rybarczykchris, nice question!

Basically, now that the code is the source of truth with Slice Machine there's by design no need to pull changes from Prismic, because Prismic isn't a source of truth anymore (for the custom type part).

In order to get changes from teammates and to collaborate with them we now expect that workflow to go through git, that is to say committing your custom type changes, and pulling them on other branches for example.

Let us know if that wasn't clear or if anything ☺️

**Comment by christianrybe** [comment]
Thanks for your swift repy @lihbr ! It makes a ton of sense and is super cool, great design! 😄 Just to be clear though I can't sync custom types as of now, can I? I can't see a place to define custom types in the slice machine UI and I've also stumbled upon this: https://github.com/prismicio/slice-machine/issues/91

**Comment by lihbr** [comment]
Right! Latest version of Slice Machine (0.0.46) doesn't include the custom type part of it. We're about to release a new version that includes this part, allowing all the modeling to be performed locally. It's already available as version 0.1.0-beta.1, upgrading _should_ be smooth but bear in mind it's still a beta 🙂

**Comment by Acen** [comment]
@lihbr Hoping to get clarification - but I (or a colleague) can go into Prismic & create a custom type, but then there's no way to retrieve that type into my local environment so I can keep them synced.

i.e. Prismic:
![image](https://user-images.githubusercontent.com/924120/186535587-2dcfecd3-b223-42a7-af55-46181a61aa71.png)

Slice machine:
![image](https://user-images.githubusercontent.com/924120/186535620-4ad32431-fb41-4974-8a53-e7a58a45105a.png)


🤔

**Comment by lihbr** [comment]
Hi there, indeed as of today there's no way to pull Custom Types from Prismic as Slice Machine now has its own Custom Type editor which is meant to be the source of truth (the online Custom Type editor is even disabled by default on new projects today)

This thread was discussing the possibility of pulling Custom Types locally before Slice Machine had its own builder. However, we're conscious that some users might be in your case and in the process of migrating, and we're working on ways to help you migrate. @comeprismic might be able to share more about it.

**Comment by Acen** [comment]
Oh, in that case I'll just delete the repo and start again.
Is there a way to see what version an existing repository might be sitting in?

**Comment by lihbr** [comment]
I'm sorry you feel like starting over, you can still keep the same repo if you want, but move your "online" Custom Types locally by copy/pasting the JSONs. Although if you feel like starting over would be faster, that also works :)

Regarding repository version: to be clear, all repos are on the same version, as-in, there's no "need to upgrade" thing à la WordPress. However, for things that are in the *process* of becoming legacy (like the online Custom Type builder), we're able to "turn them off" by default on new projects to promote the new ways of building while not blocking old users.

**Comment by ReeceM** [comment]
@Acen If you have a whole load of types or want to just pull them down locally you could probably use the a repo I made a while back when the Custom Type API was released.

It's https://github.com/reecem/custom-type-api

It works on repos that are still before slice machine as long as you make a custom type api token under the setting side.

**Comment by mattiaz9** [comment]
> This thread was discussing the possibility of pulling Custom Types locally before Slice Machine had its own builder. However, we're conscious that some users might be in your case and in the process of migrating, and we're working on ways to help you migrate. @comeprismic might be able to share more about it.

@lihbr @comeprismic Any update on this? Is it possible to pull changes from the repository now?

**Comment by bymoe** [comment]
+

**Comment by StefKors** [comment]
fyi: at the time of writing this you can at least sync **page** changes from the online editor to your codebase by copying the page json and pasting it in your `customtypes/<page-type>/index.json`.

![Screenshot 2024-12-17 at 12 00 23](https://github.com/user-attachments/assets/4f758af6-45de-4e24-bc9f-3b38a5a38955)
![Screenshot 2024-12-17 at 12 00 42](https://github.com/user-attachments/assets/126c8cc7-9b48-4292-8518-d19467888aae)
